#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PanoramaImageView.Resource", IsApplication=true)]

namespace PanoramaImageView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PanoramaImageView.Lib.Resource.Attribute.piv_enablePanoramaMode = global::PanoramaImageView.Resource.Attribute.piv_enablePanoramaMode;
			global::PanoramaImageView.Lib.Resource.Attribute.piv_invertScrollDirection = global::PanoramaImageView.Resource.Attribute.piv_invertScrollDirection;
			global::PanoramaImageView.Lib.Resource.Attribute.piv_show_scrollbar = global::PanoramaImageView.Resource.Attribute.piv_show_scrollbar;
			global::PanoramaImageView.Lib.Resource.String.ApplicationName = global::PanoramaImageView.Resource.String.ApplicationName;
			global::PanoramaImageView.Lib.Resource.String.Hello = global::PanoramaImageView.Resource.String.Hello;
			global::PanoramaImageView.Lib.Resource.Styleable.PanoramaImageView = global::PanoramaImageView.Resource.Styleable.PanoramaImageView;
			global::PanoramaImageView.Lib.Resource.Styleable.PanoramaImageView_piv_enablePanoramaMode = global::PanoramaImageView.Resource.Styleable.PanoramaImageView_piv_enablePanoramaMode;
			global::PanoramaImageView.Lib.Resource.Styleable.PanoramaImageView_piv_invertScrollDirection = global::PanoramaImageView.Resource.Styleable.PanoramaImageView_piv_invertScrollDirection;
			global::PanoramaImageView.Lib.Resource.Styleable.PanoramaImageView_piv_show_scrollbar = global::PanoramaImageView.Resource.Styleable.PanoramaImageView_piv_show_scrollbar;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int piv_enablePanoramaMode = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int piv_invertScrollDirection = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int piv_show_scrollbar = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int horizontal1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int horizontal2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int horizontal3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int vertical1 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int panoramaImageView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PanoramaImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int PanoramaImageView_piv_enablePanoramaMode = 0;
			
			// aapt resource value: 1
			public const int PanoramaImageView_piv_invertScrollDirection = 1;
			
			// aapt resource value: 2
			public const int PanoramaImageView_piv_show_scrollbar = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
